### PR TITLE
Follow PSR-2 and add doc string

### PR DESCRIPTION
**Pull request by tonyhhyip**

### CODE REVIEW

**Comment by aacotroneo** [comment]
Nice, but can you make this into 1 commit please? git rebase -i HEAD~5 or something.

**Comment by tonyhhyip** [comment]
@aacotroneo Is it a matter on 1 commit or 5 commit?

**Comment by aacotroneo** [comment]
It's just a good practice to have meaningful commits (easier to track, revert, browse, copy). It's also a single command line call, no big deal. Many repositories work like this, it's not an idea of mine.. And Im not purist either, just asking for higher level commit

**Comment by tonyhhyip** [comment]
@aacotroneo All commit are into one commit

**Pull request closed without merging**
