### PR TITLE
Onelogin/php-saml ^3.0 without mcrypt and with namespaces

### PR DESCRIPTION
**Pull request by Rkallenkoot**
With this pull request we're using the 3.0 version of the onelogin/php-saml library. This means we're no longer dependant on mcrypt which is deprecated as of PHP 7.2.

Also updated the codebase to psr-4 autoloading like most projects, added `orchestra/testbench` so we can start testing the ServiceProvider and use laravel test helpers.

I've updated the `illuminate/support` dependency to only support the supported Laravel versions, this might break current installations for projects that are not on Laravel >= 5.5

### CODE REVIEW

**Comment by Rkallenkoot** [comment]
Realised there is already a branch with _some_ of the changes I've done.

Also updated to psr-4 and added a package so we can test the ServiceProvider as well, which still makes it worth considering :)

**Comment by omitobi** [comment]
@Rkallenkoot See this: https://github.com/aacotroneo/laravel-saml2/issues/122#issuecomment-429341731 I am afraid not supporting all Laravel 5 is not a good idea. Even onelogin/php-saml v3.0.0 supports PHP 5.x (At least I remember PHP >5.3 is recommended) See the release: https://github.com/onelogin/php-saml/releases/tag/v3.0.0. How about following the updates on that issue and see where to make corrections where needed. Good efforts on this though 💪.

**Comment by Rkallenkoot** [comment]
@omitobi Cheers for the reply!

I understand that onelogin/php-saml supports PHP 5.x, but in less than 2 months PHP 5.x will reach end of life status (four months later than initially planned). See [php-version](http://php.net/supported-versions.php)

The same goes for Laravel < 5.5, as can be seen in the following table:


5.0 | Feb 4th, 2015 | Aug 4th, 2015 | Feb 4th, 2016
-- | -- | -- | --
5.1 (LTS) | Jun 9th, 2015 | Jun 9th, 2017 | Jun 9th, 2018
5.2 | Dec 21st, 2015 | Jun 21st, 2016 | Dec 21st, 2016
5.3 | Aug 23rd, 2016 | Feb 23rd, 2017 | Aug 23rd, 2017
5.4 | Jan 24th, 2017 | Jul 24th, 2017 | Jan 24th, 2018
5.5 (LTS) | Aug 30th, 2017 | Aug 30th, 2019 | Aug 30th, 2020
5.6 | Feb 7th, 2018 | Aug 7th, 2018 | Feb 7th, 2019
5.7 | Sep 4, 2018 | Feb 4th, 2019 | Sep 4th, 2019

(source: [laravel-news.com](https://laravel-news.com/laravel-release-process))

Personally I think it's not a good idea to support a language or framework version which has been "deprecated" and might even bring security issues, since they will no longer receive security updates.

PHP >= 7.1 and Laravel >= 5.5 there for make sense IMO, but that's not up me of course :)

**Comment by renepardon** [comment]
I can't install and use this package. I'm using PHP 7.2 by default and possibly 7.3 in near future... so have to fork this and maintain it by myself if it doesn't get merged into master branch

```bash
composer require aacotroneo/laravel-saml2
Using version ^0.11.1 for aacotroneo/laravel-saml2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - onelogin/php-saml v2.14.0 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
- onelogin/php-saml v2.13.0 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - onelogin/php-saml v2.12.0 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - onelogin/php-saml 2.11.0 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - onelogin/php-saml 2.10.7 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - onelogin/php-saml 2.10.6 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - onelogin/php-saml 2.10.5 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - onelogin/php-saml 2.10.4 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - onelogin/php-saml 2.10.3 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - onelogin/php-saml 2.10.2 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - onelogin/php-saml 2.10.1 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - onelogin/php-saml 2.10.0 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - aacotroneo/laravel-saml2 0.11.1 requires onelogin/php-saml ^2.10 -> satisfiable by onelogin/php-saml[2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4, 2.10.5, 2.10.6, 2.10.7, 2.11.0, v2.12.0, v2.13.0, v2.14.0].
    - Installation request for aacotroneo/laravel-saml2 ^0.11.1 -> satisfiable by aacotroneo/laravel-saml2[0.11.1].
```

cc @Rkallenkoot  @omitobi

**Comment by Rkallenkoot** [comment]
Hi @renepardon 

I'm currently also using my own fork, although there's also a onelogin/php-saml:3.0 version available in this repo.
I've also refactored a bit to the namespaced classes and added testing utils like orchestra so we can test the ServiceProvider in this library! Lets hope we can get a PHP7.2 compatible version "released" asap :)

**Comment by omitobi** [comment]
@renepardon There's a branch that targets onelogin/php-saml v3.0.0 https://github.com/aacotroneo/laravel-saml2/tree/one-login-3 already. You many follow the discussion here: https://github.com/aacotroneo/laravel-saml2/issues/122

**Comment by renepardon** [comment]
@Rkallenkoot @omitobi I couldn't wait so I've created a completely new version on my own today. 

Travis run's for PHP 7.1/7.2/7.3 https://packagist.org/packages/renepardon/laravel-saml2

**Comment by aacotroneo** [comment]
as a first step, I cleaned up the one-login-3 branch so we can release a version with the minimal set of changes.

Let's keep the psr-4 vs psr-0 battle as a separate issue from the upgrade to v3. It's hard to deal with 'opinionated' changes in public libraries, because for every dev that likes one style, there's another one that likes it differently.

Also not a fan of dropping support for versions just because. This is a small library, the least requirements the better... let Laravel and OneLogin set the restrictions.

**Comment by Rkallenkoot** [comment]
Closing this since it's no longer needed!

Thanks for all your work :)

**Pull request closed without merging**
