### PR TITLE
Change composer requirements to allow Laravel 5.1

### PR DESCRIPTION
**Pull request by samlev**
Composer currently fails to install this package on Laravel 5.1

### CODE REVIEW

**Comment by aacotroneo** [comment]
Great!!
Could you make this to be 1 commit? (git rebase -i HEAD~2)

**Comment by samlev** [comment]
ok, closing this one, and fixing it up

**Comment by aacotroneo** [comment]
fyi.. if you've done a git rebase -i, plus a git push -f, PR updates automatically :) github is that awesome! I can tell you  what commands to run if you need them.. dont waste much time on this one! I was just being purist about making this 1 commit!

**Comment by samlev** [comment]
I ran the original merge request off my master, and this time I did it off
a branch, so it's easier to manage.

On Mon, Aug 17, 2015 at 5:27 PM, Alejandro Cotroneo <
notifications@github.com> wrote:

> fyi.. if you've done a git rebase -i, plus a git push -f, PR updates
> automatically :) github is that awesome! I can tell you what commands to
> run if you need them.. dont waste much time on this one! I was just being
> purist about making this 1 commit!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aacotroneo/laravel-saml2/pull/8#issuecomment-131982281>
> .
>



-- 
Samuel Levy
Freelance Software Engineer

Mob (AU): +614 2457 5194
Mob (US): +1(281) 386-6195
http://www.samuellevy.com
*Contact me <sam+jobs@samuellevy.com> for contracting and consulting rates*

**Comment by aacotroneo** [comment]
yep, good one!!

**Pull request closed without merging**
