### PR TITLE
added support for laravel 5.1

### PR DESCRIPTION
**Pull request by AlexStorm1313**

### CODE REVIEW

**Comment by aacotroneo** [comment]
hmm.. We can't do this - it will break all compatibility to laravel 5.0 users, and all people who is still on php 5.4 (that's why tests are failing btw).

Isn't this library working for you for 5.1? `>=5.0` should match 5.1.  If it doesn't work it will be nice to fix it, but with breaking changes.If we are to introduce breaking changes, we should bump version to 1.0.0 (semantic versioning).

thanks for contributing!

**Comment by AlexStorm1313** [comment]
The problem for me was that when i had laravel 5.1 installed composer would check is the versions are correct and failed on the version number, now i managed to fix it by manually changing the version in the composer.json file. maybe you could use different branches to iron out some of these errors which are caused just my version numbers.

**Comment by aacotroneo** [comment]
yes, but what are the versions that fail... shouldn't the existing
'>=5.0.0' be compatible to 5.1 ? can you make a clean composer install  of
your project and paste the errors?

If we don't find another solution, I think that bumping the version to
1.0.0 should be enough (we can merge it in the master)

2015-12-17 10:09 GMT-03:00 Alex Brasser <notifications@github.com>:

**Comment by syphernl** [comment]
FWIW it works fine as-is on Laravel 5.2

**Comment by scs2771** [comment]
With Laravel 5.1.29 I'm getting this error:
 Problem 1
    - aacotroneo/laravel-saml2 0.6.0 requires onelogin/php-saml 2.6.1 -> satisfiable by onelogin/php-saml[2.6.1].
    - onelogin/php-saml 2.6.1 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - Conclusion: remove laravel/framework v5.1.29
    - Conclusion: don't install laravel/framework v5.1.29
    - Conclusion: don't install laravel/framework v5.1.28
    - Conclusion: don't install laravel/framework v5.1.27
    - Conclusion: don't install laravel/framework v5.1.26
    - Conclusion: don't install laravel/framework v5.1.25
    - Conclusion: don't install laravel/framework v5.1.24
    - Conclusion: don't install laravel/framework v5.1.23
    - Conclusion: don't install laravel/framework v5.1.22
    - Conclusion: don't install laravel/framework v5.1.21
    - Conclusion: don't install laravel/framework v5.1.20
    - Conclusion: don't install laravel/framework v5.1.19
    - Conclusion: don't install laravel/framework v5.1.18
    - Conclusion: don't install laravel/framework v5.1.17
    - Conclusion: don't install laravel/framework v5.1.16
    - Conclusion: don't install laravel/framework v5.1.15
    - Conclusion: don't install laravel/framework v5.1.14
    - Conclusion: don't install laravel/framework v5.1.13
    - Conclusion: don't install laravel/framework v5.1.12
    - Conclusion: don't install laravel/framework v5.1.11
    - Conclusion: don't install laravel/framework v5.1.10
    - Conclusion: don't install laravel/framework v5.1.9
    - Conclusion: don't install laravel/framework v5.1.8
    - Conclusion: don't install laravel/framework v5.1.7
    - Conclusion: don't install laravel/framework v5.1.6
    - Conclusion: don't install laravel/framework v5.1.5
    - Conclusion: don't install laravel/framework v5.1.4
    - Conclusion: don't install laravel/framework v5.1.3
    - Conclusion: don't install laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.1
    - aacotroneo/laravel-saml2 0.5.0 requires illuminate/support 5.0.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - aacotroneo/laravel-saml2 0.5.1 requires illuminate/support 5.0.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - aacotroneo/laravel-saml2 0.0.1 requires illuminate/support 4.2.* -> satisfiable by illuminate/support[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - aacotroneo/laravel-saml2 0.0.2 requires illuminate/support 4.2.* -> satisfiable by illuminate/support[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.17|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.1.0
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.1.0
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9].
    - Installation request for aacotroneo/laravel-saml2 * -> satisfiable by aacotroneo/laravel-saml2[0.0.1, 0.0.2, 0.5.0, 0.5.1, 0.6.0].

**Comment by aacotroneo** [comment]
the requested PHP extension mcrypt is missing from your system- do you
have it available on PHP?

**Comment by scs2771** [comment]
Bah I missed that in the error message. That's what I get for composer update outside of homestead for my laravel apps. Sorry about that and thanks for pointing that out.

**Comment by aacotroneo** [comment]
np!! :)

2016-02-03 12:20 GMT-03:00 scs2771 <notifications@github.com>:

**Comment by danmichaelo** [comment]
By leaving this PR open, it seems like this library doesn't support Laravel 5.1, while it does in fact work perfectly fine with Laravel 5.1, 5.2 and 5.3. @aacotroneo : can you please close this as invalid?

**Pull request closed without merging**
