### PR TITLE
Exposed sessionIndex and nameId to be able to logout correctly

### PR DESCRIPTION
**Pull request by mickael83**
Hi,

As we discussed I exposed the sessionIndex and nameId in order to be able to save those values in the  Saml2LoginEvent event, I changed the Saml2Controller and Saml2Auth class to receive the returnUrl, sessionIndex and nameId as parameters and finally I added the retrieveParametersFromServer option in the configuration files.

I tested those changes with my ADFS installation and is all working ok.

Best regards

### CODE REVIEW

**Comment by aacotroneo** [comment]
hi, the PR looks good, but it's breaking our (little) tests. That is because you added an extra dependency which is `config` to Saml2Auth. You may pass the config as a parameter from the controller.
btw, try to remove the 'fix' commits from the PR.. it's not that bad, but providing that we still haven't merged it's cleaner for the history!

**Comment by mickael83** [comment]
I just made the changes you suggested. Can you please verify if it is ok now. Thanks!

**Comment by aacotroneo** [comment]
there's 1 failing test only now.. you can check by clicking ^^^
``` continuous-integration/travis-ci/pr — The Travis CI build failed```
https://travis-ci.org/aacotroneo/laravel-saml2/jobs/109363264

You can also run the tests... `phpunit`

**Comment by mickael83** [comment]
Ok I think it's all good now :)

**Comment by aacotroneo** [comment]
merging!! thanks @mickael83

**Pull request merged**
